= Backend

== Topology
Since all clients must maintain the exact same state, messages must be delivered in-order.
To facilitate this, the backend servers are sharded by guild, allowing each server to maintain the exact order of messages for their guilds.
However, clients generally participate in multiple guilds, necessitating  

[#auth]
== Authentication & Authorization
Users are authenticated using a token known only to that user.
Tokens are arbitrary length byte sequences (currently 16 random bytes).

Each user has an allowlist for each guild, which dictates who they will receive messages from.
User's can only edit their own allowlist.
The OR of all users' allowlists for a guild dictates whether a user's message will be stored by the backend, and whether they can subscribe to the guild.

When a user with the correct permissions decides to remove a user, (if the message is valid) each user in the guild removes the user from their guild allowlist.
This immediately blocks the offending user from wasting a user's bandwidth with bogus messages.
However, since not all users are online, the offending user may still be on other user's allowlists, allowing them to waste the storage of the backend.
This is not a significant issue however, as the backend must already ratelimit events to prevent normal denial of service attacks.
Once all users come online once, the user will be removed from all guild allowlists, blocking them from listening to or sending events.

If a user tries to maliciously block another user, they won't get very far, as the message to block the user will be rejected by other users in the guild, and the user will remain on their allowlists.

Futher, we don't need to enforce the consistency between the user id for each connection, and the messages that connection sends.
If users receive messages from a random uuid, they will simply drop them.
Since the original user uuid was already authorized, this does not break the authorization system.

== Database 
All encrypted messages are stored in MongoDB.

The messages are stored in chronological order per guild indexed by timestamp.
Internally, we have a `messages` collection in the `carbide` database.
Documents have a `guildID`, `evtID`, `ts`, and `message` fields.

== Protocol
The webapp talks to the backend over websockets.

Events are sent as `websocket.BinaryMessage`, as the underlying encrypted messages are, of course, binary.

=== Heartbeat
When a client receives a heartbeat, it should immediately respond with a Heartbeat Ack.
Sent by the backend only.
----
EvtType:  0x00 - Heartbeat

M = EvtType
----


=== Heartbeat Ack
Sent by clients only.
----
EvtType:  0x01 - Heartbeat Ack

M = EvtType
----


=== Error
Sent by the backend only.
----
EvtType:  0x02 - Error
Error:    A byte value. One of:
            0x00 - Failed to authenticate. You will be disconnected.
            0x01 - Not in guild allowlist. (Cannot subscribe or send message)

M = EvtType || Error
----


=== Data
Sent by clients and the backend.
----
EvtType:    0x03 - Data
GuildUUID:  128-bit UUID of the guild
EvtUUID:    An UUID set by the client when sending this message that uniquely identifies this event.
Timestamp:  Unix millis of when the message was broadcast by the backend (64-bit, big endian)
            This field is only filled by the backend. When sent by the client, it SHOULD be left as 0.
Message:    The bytes of the message itself

M = EvtType || GuildUUID || EvtUUID || Timestamp || Message
----


=== Data Ack
An ack acknowledges that a sender's Data event has been distributed.
This indicates to the sender that it should apply the referenced mutation itself.
Using an Ack means we don't break the strong ordering of messages, and means we don't have to add ourselves to our own TX session.
Sent by the backend only.
----
EvtType:    0x04 - Data Ack
GuildUUID:  128-bit UUID of the guild
EvtUUID:    The EvtUUID set in the corresponding Data event
Timestamp:  Unix millis of when the corresponding event was broadcast by the backend (64-bit, big endian)

M = EvtType || GuildUUID || EvtUUID || Timestamp
----


=== Register
Generate new user uuid and corresponding <<auth,token>>.
The backend will return a filled version of the event.
Sent by clients and the backend.
----
EvtType:   0x05 - Register
UserUUID:  The new uuid of the user. SHOULD be set to 0 when trasmitted by the client.
Token:     The token to prove ownership of the uuid to the server. SHOULD be left empty by the client.

M = EvtType || UserUUID || Token
----


=== Authenticate
Sent by clients only.
[subs=normal]
----
EvtType:  0x06 - Authenticate
Token:    The token. See <<auth>>.

M = EvtType || Token
----


=== Subscribe guilds
Subscribe the client to the specified guilds.
Sent by clients only.
----
EvtType:       0x07 - Subscribe guilds
GuildUUID[n]:  The UUID of a guild to subscribe to

M = EvtType || GuildUUID[0] || ... || GuildUUID[n-1]
----


=== Add users
Add the specified users to the user's guild allowlist, as described in <<auth>>.
Sent by clients only.
----
EvtType:      0x08 - Add users
GuildUUID:    128-bit UUID of the guild
UserUUID[n]:  128-bit UUID of the user

M = EvtType || GuildUUID || UserUUID[0] || ... || UserUUID[n-1]
----


=== Remove users
Remove the specified users to the user's guild allowlist, as described in <<auth>>.
Sent by clients only.
----
EvtType:      0x09 - Remove users
GuildUUID:    128-bit UUID of the guild
UserUUID[n]:  128-bit UUID of the user

M = EvtType || GuildUUID || UserUUID[0] || ... || UserUUID[n-1]
----
