= Encryption
:toc:

== The Tungsten Ratchet
=== Background
The Tungsten Ratchet builds on both Signal's Double Ratchet Algorithm, and Matrix's Megolm Group Ratchet.

The Double Ratchet Algorithm is unsuitable, as it requires that users encrypt their messages to each recipient in a group, which could be over 1000 people.
The Megolm Group Ratchet fixes this by having one outbound ratchet, and many inbound ratchets.
However, it doesn't have a mechanism for break-in recovery, and only provides "partial" forward secrecy.

The Tungsten Ratchet takes the best from both ratchets.
It provides break-in recovery and forward secrecy, while maintaining a single outbound session.

=== Overview
Each user maintains an outbound session for encrypting their own messages, and an inbound session for each user.
Each session contains a root ratchet, a symmetric ratchet, a UUID.
A "TX" session additionally contains signing keys (EC and PQ) and key exchange privkeys (EC and PQ).
A "RX" session additionally contains verifying keys (EC and PQ) and key exchange pubkeys (EC and PQ), which both correspond to the pubkeys of the sender's tx sesion. For each sender, all user's RX sessions should be identical.

Every message is signed with Ed25519 and Dilithium2 signatures.
Forward secrecy is provided by the ratchets.
Break-in recovery is provided by exchanging new keypairs, as shown in <<_root_key_ratchet>>.

=== Symmetric-key ratchet 
This part describes a symmetric-key ratchet that is an exact copy of the Signal protocol's symmetric-key ratchet.

=== Root-key ratchet
Each user has a DH and kyber keypair.
When a user wants to update the chain/root key of their symmetric ratchet, they take the following steps.

. Generate a new DH and kyber keypair
. For each user in the group, calculate the shared secret of their current pubkey with our new privkey (dh)
. For each user in the group, encrypt a new random key with a HKDF derived key from above shared secret (dh) and encrypt a random key using kyber kem.
. Send a message with our new public key and each encrypted key (labelled with the corresponding recipient) (the message should be signed)
. Advance the root ratchet with the random keys encrypted with kyber and dh shared secrets (hmac)
. Use the output from advancing the ratchet as the root key for a new symmetric-key ratchet

When a user receives this message, they shall:

. Update the corresponding user's current public keys
. Calculate the shared secret with our privkey and the received pubkey (kyber & dh)
. Decrypt the new keys with the the HKDF-derived keys from the shared secrets
. Advance the root ratchet with the decrypted keys (hmac)
. Use the output from advancing the ratchet as the root key for a new symmetric-key ratchet

=== Session initiation
In order for a person to be added to a group, they must receive copies of symmetric and root ratchets for each user.
The group must also create a new "RX" session for them, with verifying keys and a new symmetric and root ratchet.

For security purposes, no message can be sent that can trigger tungsten to create a new rx session which would be used as a recipient for encrypted messages.
Instead, the application must make an API call.

Session initation requires the following steps:

. Each user generates an ephemeral DH and kyber keypair, and uploads their public key to the server
. Each user retrieves the other's public keys, and hashes all public keys together. Both users then verify they have the same hash. (This prevents MITM attacks)
. The original user packages up their RX sessions and sends it to the new user, encrypting it with a key derived from the shared secrets of DH and kyber
. The new user generates a new TX session (including uuid, signing and key exchange keys, and new ratchets) and sends the public values to the original user
. The original user sends a "create user" message to the group, with the new rx session attached.

=== Message formats
==== Data
The format of normal encrypted data. 
----
UUID:         128-bit UUID of the sender
MsgType:      0x00 - Data
Nonce:        Nonce for encryption of payload
Payload:      Encrypted payload
Signature:    EC signature over all preceding bytes in message
SignaturePQ:  Post-quantum signature over the same bytes as Signature

M = UUID || MsgType || Nonce || Payload || Signature || SignaturePQ
----

==== Ratchet update
The format of a ratchet update
----
UUID:             128-bit UUID of the targeted user
KeyCiphertext:    The ciphertext resulting from the encapsulation of the DH part of the root ratchet update
KeyCiphertextPQ:  The ciphertext resulting from the encapsulation of the Kyber part of the root ratchet update

Updates[n] = UUID || KeyCiphertext || KeyCiphertextPQ
----
----
UUID:         128-bit UUID of the sender
MsgType:      0x01 - Ratchet update
UpdatesLen:   The number of subsequent Update (big endian, 64-bit)
Updates[]:    A slice (array) of updates (defined above)
Signature:    EC signature over all preceding bytes in message
SignaturePQ:  Post-quantum signature over the same bytes as Signature

M = UUID || MsgType || Pubkey || PubkeyPQ || UpdatesLen || Updates[0] || ... || Updates[n-1] || Signature || SignaturePQ
----

=== Export format
==== TX Session
The format of an exported tx session
----
UUID:              128-bit UUID of the tx session
SigningKey:        EC private key used for signing messages
SigningKeyPQ:      Post-quantum private key used for signing messages
SymmetricRatchet:  Current chain key of the symmetric ratchet
RootRatchet:       Current chain key of the root ratchet
CurPrivkey:        Current DH private key for receiving ratchet updates
CurPrivkeyPQ:      Current post-quantum private key for receiving ratchet updates
CurPubkeyPQ:       Current post-quantum public key for receiving ratchet updates
RxSessionsLen:     The number of subsequent RxSessions (big endian, 64-bit)
RxSession[n]:      A slice (array) of RxSessions (defined below)

M = UUID || SigningKey || SigningKeyPQ || SymmetricRatchet || RootRatchet || CurPrivkey || CurPrivkeyPQ || CurPubkeyPQ || RxSessionsLen || RxSessions[0] || ... || RxSessions[n-1]
----

==== RX Session
The format of an exported rx session
----
UUID:              128-bit UUID of sender to this rx session
VerifyingKey:      EC public key used for verifying signed messages
VerifyingKeyPQ:    Post-quantum public key used for verifying signed messages
SymmetricRatchet:  Current chain key of the symmetric ratchet
RootRatchet:       Current chain key of the root ratchet
CurPubkey:         Current DH public key used for sending ratchet updates
CurPubkeyPQ:       Current post-quantum public key used for sending ratchet updates

M = UUID || VerifyingKey || VerifyingKeyPQ || SymmetricRatchet || RootRatchet || CurPubkey || CurPubkeyPQ
----

=== Security considerations

== Multi-device support
Multiple devices can be supported using a tungsten group between each of them.
When new key material is generated, it is supplied to the rest of the group, so they derive the same keys as the local device.
The materials are timestamped, so that if other devices are offline, they can reconstruct the chronology of other sessions.

== Primitives
All primitives should have at least 128-bit pre- and post-quantum security.

[cols=5*]
|===
|Type |Algorithm |Implementation |Pre-quantum security (bits) |Post-quantum security (bits)

|PBKDF
|Argon2id
|golang.org/x/crypto/argon2
|n/a
|n/a

|KDF for symmetric ratchet
|HMAC-SHA256
|crypto/hmac & crypto/sha256
|256 (preimage resistance of sha256)
|128 (preimage resistance of sha256)

|Symmetric Encryption
|XSalsa20 with Poly1305
|golang.org/x/crypto/nacl/secretbox
|256
|128

|Key-exchange
|X25519
|github.com/cloudflare/circl
|128
|0 (mitigated by post-quantum key exchange)

|Post-quantum key-exchange
|Kyber 768
|github.com/cloudflare/circl
|0 (algorithm is not thoroughly tested, mitigated by pre-quantum key exchange)
|128

|Signature
|Ed25519
|github.com/cloudflare/circl
|128
|0 (mitigated by post-quantum signature)

|Post-quantum signature
|Dilithium Mode 2
|github.com/cloudflare/circl
|0 (algorithm is not thoroughly tested, mitigated by pre-quantum signature)
|128

|===
