= Encryption

== The Rye Algorithm
=== Symmetric-key ratchet 
This part describes a symmetric-key ratchet that is an exact copy of the Signal protocol's symmetric-key ratchet.

=== Root-key ratchet
Each party has a DH and kyber keypair.
When a party wants to update the chain/root key of their symmetric ratchet, they take the following steps.

. Generate a new DH and kyber keypair
. For each user in the group, calculate the shared secret of their current pubkey with our new privkey (dh)
. For each user in the group, encrypt a new random key with a HKDF derived key from above shared secret (dh) and encrypt a random key using kyber kem.
. Send a message our new public key and each encrypted key (labelled with the corresponding recipient) (the message should be signed)
. Advance the root ratchet with the random keys encrypted with kyber and dh shared secrets (hmac)
. Use the output from advancing the ratchet as the root key for a new symmetric-key ratchet

When a party receives this message, they shall:

. Update the corresponding party's current public keys
. Calculate the shared secret with our privkey and the received pubkey (kyber & dh)
. Decrypt the new keys with the the HKDF-derived keys from the shared secrets
. Advance the root ratchet with the decrypted keys (hmac)
. Use the output from advancing the ratchet as the root key for a new symmetric-key ratchet

== Primitives
All primitives should have at least 128-bit post quantum security

[cols=5*]
|===
|Type |Algorithm |Implementation |Pre-quantum security (bits) |Post-quantum security (bits)

|PBKDF
|Argon2id
|golang.org/x/crypto/argon2
|
|

|Hash
|SHA-256
|crypto/sha256
|
|

|KDF for symmetric ratchet
|HMAC-SHA256
|crypto/hmac & crypto/sha256
|
|

|Symmetric Encryption
|XSalsa20 with Poly1305
|golang.org/x/crypto/nacl/secretbox
|256
|128

|Key-exchange
|X25519
|github.com/cloudflare/circl
|128
|0 (mitigated by post-quantum key exchange)

|Post-quantum key-exchange
|Kyber 768
|github.com/cloudflare/circl
|0 (algorithm is not thoroughly tested, mitigated by pre-quantum key exchange)
|128

|Signature
|Ed25519
|github.com/cloudflare/circl
|128
|0 (mitigated by post-quantum key exchange)

|Post-quantum signature
|Dilithium Mode 2
|github.com/cloudflare/circl
|0 (algorithm is not thoroughly tested, mitigated by pre-quantum key exchange)
|128

|===
